on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: create linux amd64 release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: 1.13
